pipeline{
    agent{
        label "jenkins-server"
    }
    stages{
        stage('Clone Repository'){
            steps{
                git branch: 'main', url:'https://github.com/PriyeshPandey07/Visa-advisor-project.git', credentialsId: 'git-creds'
            }
        }
        stage('Install and Migrate'){
            steps{
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                venv/bin/pip install --upgrade pip
                venv/bin/pip install -r requirements.txt
                venv/bin/python manage.py makemigrations || true
                venv/bin/python manage.py migrate || true
                '''
            }
        }
        stage("ECR Create, Image Build & Push"){
            steps{
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'vishwa']
                ]) {
                    sh "aws sts get-caller-identity"
                    sh "aws ecr describe-repositories --repository-names visa-advisor \
                        --region ap-south-1 || true"
                    sh "aws ecr create-repository \
                        --repository-name visa-advisor \
                        --region ap-south-1" 
                    sh "aws ecr get-login-password --region ap-south-1 | \
                        docker login --username AWS --password-stdin 985671710454.dkr.ecr.ap-south-1.amazonaws.com"
                    sh "docker build -t visa-advisor ."
                    sh "docker tag visa-advisor 985671710454.dkr.ecr.ap-south-1.amazonaws.com/visa-advisor:latest"
                    sh "docker push 985671710454.dkr.ecr.ap-south-1.amazonaws.com/visa-advisor:latest"
                }
            }
        }
        stage("TRIVY"){
            steps{
                sh "trivy image 985671710454.dkr.ecr.ap-south-1.amazonaws.com/visa-advisor:latest > trivy.txt" 
            }
        }
        stage('Install Ingress') {
            steps {
                sh "export KUBECONFIG=/var/lib/jenkins/.kube/config"
                sh "kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/aws/deploy.yaml"
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                dir('K8s') {
                    sh "kubectl apply -f deployment.yaml"
                    sh "kubectl apply -f service.yaml"
                    sh "kubectl apply -f autoscaling.yaml"
                    sh "kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=180s"
                    sh "kubectl apply -f ingress.yaml"
                }
            }
        }
        stage('Monitoring using Helm') {
            steps {
                sh "helm repo add prometheus-community https://prometheus-community.github.io/helm-charts"
                sh "helm repo update"
                sh "helm install monitoring prometheus-community/kube-prometheus-stack"
            }
        }
    }
}
