# Generated by Django 3.2 on 2024-02-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('adress', models.TextField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.TextField(max_length=100)),
                ('phonenumber', models.PositiveIntegerField()),
                ('password', models.TextField(max_length=20)),
            ],
        ),
    ]
