# Generated by Django 3.2 on 2024-02-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advisor',
            new_name='Client',
        ),
    ]
