# Generated by Django 3.2 on 2024-02-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0002_rename_advisor_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='client',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phonenumber',
        ),
    ]
