# Generated by Django 3.2 on 2024-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0003_auto_20240212_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
