# Generated by Django 3.2 on 2024-02-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0004_auto_20240212_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.TextField(null=True)),
                ('phoneno', models.IntegerField(null=True)),
                ('password', models.TextField(null=True)),
                ('experience', models.TextField(null=True)),
                ('country_specialization', models.TextField(null=True)),
                ('education', models.TextField(null=True)),
            ],
        ),
    ]
