# Generated by Django 3.2 on 2024-02-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0005_visaadvisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='username',
        ),
    ]
