# Generated by Django 3.2 on 2024-02-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0006_rename_name_client_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='name',
        ),
    ]
