# Generated by Django 3.2 on 2024-02-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0007_rename_username_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='username',
        ),
    ]
