# Generated by Django 3.2 on 2024-02-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0011_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
