# Generated by Django 3.2 on 2024-02-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0012_remove_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
