# Generated by Django 3.2 on 2024-02-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0013_auto_20240214_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
