# Generated by Django 3.2 on 2024-02-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0014_client_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaadvisor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visaadvisor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visaadvisor',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visaadvisor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
