# Generated by Django 3.2 on 2024-02-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0015_auto_20240214_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visaadvisor',
            old_name='name',
            new_name='username',
        ),
    ]
