# Generated by Django 3.2 on 2024-02-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0016_rename_name_visaadvisor_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerquerry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('query', models.TextField()),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desire.visaadvisor')),
            ],
        ),
    ]
