# Generated by Django 3.2 on 2024-02-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0017_customerquerry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquerry',
            name='adviser',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='desire.visaadvisor'),
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharcard', models.ImageField(upload_to='clientimg')),
                ('paancard', models.ImageField(upload_to='clientimg')),
                ('passport', models.ImageField(upload_to='clientimg')),
                ('adviser', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='desire.visaadvisor')),
            ],
        ),
    ]
