# Generated by Django 3.2 on 2024-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0018_auto_20240219_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='email',
            field=models.TextField(default=True),
        ),
    ]
