# Generated by Django 3.2 on 2024-02-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0020_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviserquerry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('query', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
